config/routes.rb
Rails.application.routes.draw do
  get 'song_search/index'

  get 'playlist_audio_player/index'

  get 'playlist_songs/index'

  get 'playlist_songs/new'

  get 'playlist_songs/show'

  get 'playlists/index'

  get 'playlists/new'

  get 'audio_player/index'

  get 'feed/index'

  devise_for :users
  resources :playlist_audio_player
  resources :users
  resources :playlists
  resources :songs
  resources :playlist_songs do
    get "delete"
  end
  
  resources :playlist do 
    resources :playlist_songs    
  end
  resources :playlist do 
    resources :songs do 
      resources :playlist_songs
    end
  end

  resources :playlist do 
    resources :song_search 
  end

  
  resources :playlist do 
    resources :playlist_audio_player
  end
  resources :songs do 
    resources :audio_player
  end
  root to: 'feed#index'
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs
  acts_as_likeable
  validates_presence_of :user
end

app/models/playlist_song.rb
class PlaylistSong < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :song
  validates_presence_of :playlist
  validates_presence_of :song
  validates_uniqueness_of :song
end

app/models/song.rb
class Song < ActiveRecord::Base 
  validates_uniqueness_of  :api_id
  validates_presence_of :api_id
  validates_presence_of :art_work
  validates_uniqueness_of  :source_url
  validates_presence_of :title 
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs
  scope :starts_with, -> (title) { where("title like ?", "%#{title}%")}
  def self.save_data_from_api(blog)
    offset = 0
    client = Tumblr::Client.new :consumer_key => 'SC33bEI1MgbSTpMgI9ORph6mezAaTCm1uMYG81iOUNWJ4CMJ9f'
    iresult = client.posts "#{blog}", :type => 'audio', :filter => 'raw'
    total_post = iresult["total_posts"]/20
    total_post.times do |i|

      result = client.posts "#{blog}", :type => 'audio', :filter => 'raw',:offset => offset += 20
      feed_data = result["posts"]
      total_post = result["total_posts"]/20
      songs = feed_data.map do |post|
        song = Song.new
        song.api_id = post["id"]
        song.art_work = post["album_art"]
        if post["album_art"].blank?
          song.source_url = post["source_url"]
        else
          song.source_url = post["audio_url"]
        end
        if post["song_name"].blank?
          song.title =  post["summary"]
        else
          song.title = post["song_name"]
        end
        # set name value however you want to do that
        song.save
        song
      end 
    
    end 

  end






  def self.update_data_from_api
    client = Tumblr::Client.new :consumer_key => 'SC33bEI1MgbSTpMgI9ORph6mezAaTCm1uMYG81iOUNWJ4CMJ9f'
    result = client.posts 'thedigitaltraphouse2.tumblr.com', :type => 'audio', :filter => 'raw'
    feed_data = result["posts"]
    total_post = result["total_posts"]/20
    songs = feed_data.map do |post|
      song = Song.new
      song.api_id = post["id"]
      song.art_work = post["album_art"]
      if post["album_art"].blank?
        song.source_url = post["source_url"]
      else
        song.source_url = post["audio_url"]
      end
      if post["song_name"].blank?
        song.title =  post["summary"]
      else
        song.title = post["song_name"]
      end
      # set name value however you want to do that
      song.save
      song
    end     
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: [:user,:curator, :admin]
  after_initialize :set_default_role, :if => :new_record?
  acts_as_liker
  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/audio_player_controller.rb
class AudioPlayerController < ApplicationController
  def index
    @track = Song.find(params[:song_id])
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def index
    @feed = Song.order('RANDOM()').paginate(page: params[:page], per_page: 15)
  end
end

app/controllers/playlist_audio_player_controller.rb
class PlaylistAudioPlayerController < ApplicationController
  def index
    @tracks = PlaylistSong.where(:playlist_id => params[:playlist_id])
  end
end

app/controllers/playlist_songs_controller.rb
class PlaylistSongsController < ApplicationController
  def index
    @playlist_songs = PlaylistSong.where(:playlist_id => params[:playlist_id])


  end

  def new
    @feed = Song.order('RANDOM()').paginate(page: params[:page], per_page: 15)
    @playlist_song = PlaylistSong.new
  end
  def create
    @playlist_song = PlaylistSong.new
    @playlist_song.playlist_id = params[:playlist_id]
    @playlist_song.song_id = params[:song_id]
    @playlist_song.save
    if @playlist_song.save
      flash[:notice] = "This song has been saved to the playlist"
      redirect_to :back
      
    else
      flash[:succes] = "Please retry again"
      render 'new'
    end
    
  end

  def show
  end
   def delete
    @playlist_song.song_id = PlaylistSong.find(params[:song_id])
  end
  def destroy    
    
    @playlist_song = PlaylistSong.find_by(:id => params[:id])
    @playlist_song.destroy   
    redirect_to :back
  end

  private
  def playlist_songs_params
    params.require(:playlistSong).permit(:playlist_id , :song_id)
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  def index
    @playlists = Playlist.where(:user_id => current_user.id)
  end

  def new 
    @playlist = Playlist.new
  end
  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.user_id = current_user.id  
    if @playlist.save
      flash[:notice] = "The playlist was saved"

    else
     flash[:succes] = "The playlist was not saved"
    end
    
  end
  def show
    @feed = Song.order('RANDOM()').paginate(page: params[:page], per_page: 21)
    @playlist = Playlist.find(params[:id])
  end
  def edit
    @playlist = Playlist.find(params[:id])
  end

 def update
  @playlist = Playlist.find(params[:id])
  if @playlist.user_id == current_user.id
    @playlist.update(playlist_params)
  if @playlist.save
    flash[:notice] = "The playlist was successfully updated"
    render 'save'
  else
    render 'edit'
    flash[:success] = "Something that went wrong please try again"
  end
    
  else
     flash[:success] = "Sorry you're not the host of the party"
     redirect_to party_path(params[:id])

  end
  

 end
   private
  # Use callbacks to share common setup or constraints between actions.
  def set_playlist
    @playlist = Playlist.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def playlist_params
    params.require(:playlist).permit(:name,:user_id,:playlist_cover,:publish)
  end
end

app/controllers/song_search_controller.rb
class SongSearchController < ApplicationController
  def index
    @results = Song.starts_with(params[:search])

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all
    authorize User
  end

  def show
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/audio_player/_index.html.haml
.audio-player
  %h2= @track.title
  %audio#audio-player{:autoplay => true , :controls => "controls", :src => "#{@track.source_url}", :type => "audio/mp3"}
    / @end .audio-player
  / @end #content
/ @end #w
:javascript
  $(function(){
    $('#audio-player').mediaelementplayer({
      alwaysShowControls: true,
      features: ['playpause','progress','volume'],
      audioVolume: 'horizontal',
      audioWidth: 1000,
      audioHeight: 70,
      enableAutosize: true,
      iPadUseNativeControls: true,
      iPhoneUseNativeControls: true,
      AndroidUseNativeControls: true
    });
  });

app/views/audio_player/index.js.erb
$("#music_player").html("<%= escape_javascript(render 'index') %>")

app/views/feed/index.html.haml
.container
  .row
    .col-s12
      - @feed.each do |post|   
        .col-s3
          .card
            .card-image.waves-effect.waves-block.waves-light
              %img.activator{:alt => "#{post.title}", :src => "#{post.art_work}"}/
            .card-content
              %span.card-title.activator.grey-text.text-darken-4= post.title
               
               
              %p
                %a{:href => "#"} This is a link
            .card-reveal
              %span.card-title.grey-text.text-darken-4= post.title
                
              %p Here is some more information about this product that is only revealed once clicked on.
      
      = will_paginate @feed 
  
  


#product-modal.modal.fade

app/views/layouts/_footer_nav_bar.html.haml
.navbar.navbar-default.navbar-fixed-bottom
  .container  
    #playlist_player
    #music_player
    

app/views/layouts/_mat_nav.html.haml
%ul#slide-out.side-nav.fixed
  %li
    .user-view
      .background
        %img{:src => ""}/
      %a{:href => "#!user"}
        %img.circle{:src => ""}/
      %a{:href => "#!name"}
        %span.white-text.name John Doe
      %a{:href => "#!email"}
        %span.white-text.email jdandturk@gmail.com
  %li
    %a{:href => "#!"}
      %i.material-icons> cloud
      First Link With Icon
  %li
    %a{:href => "#!"} Second Link
  %li
    .divider
  %li
    %a.subheader Subheader
  %li
    %a.waves-effect{:href => "#!"} Third Link With Waves
%a.button-collapse{"data-activates" => "slide-out", :href => "#"}
  %i.material-icons menu

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
- if user_signed_in?
  %li.nav-item.active= link_to 'Discovery', "#"
  %li.nav-item.active= link_to 'Recommendation', "#"
  %li.nav-item.active= link_to 'Favourites',"#" 
  %li.nav-item.active=  link_to "New Play%list" ,new_play%list_path,  remote: true,"data-target" => "#product-modal", "data-toggle" => "modal"
  %li.nav-item.active= link_to "Play%lists" , play%lists_path
  %li.nav-item.dropdown
    %a#navbarDropdownMenuLink.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "http://example.com"}
      Dropdown link
    .dropdown-menu{"aria-labelledby" => "navbarDropdownMenuLink"}
      %li.dropdown-item= link_to 'Edit account', edit_user_registration_path
      %li.dropdown-item= link_to 'Sign out', destroy_user_session_path, :method=>'delete'
      

- else
  %li.nav-item.active= link_to 'Trending', "#"
  %li.nav-item.active= link_to 'Explore', "#"
  %li.nav-item.active= link_to 'Sign in', new_user_session_path
  %li.nav-item.active= link_to 'Sign up', new_user_registration_path
- if user_signed_in?
  - if current_user.admin?
    %li.nav-item.active= link_to 'Users', users_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Korujams'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Korujams'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield
  
    

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/playlist_audio_player/_index.html.haml
.container 
  .row
    .col-md-12
      %audio{:autoplay => "autoplay",:controls => "controls"}
                 
        - @tracks.each do |post|          
          %source{:src =>  "#{post.song.source_url}", :title => "#{post.song.title}", :type => "audio/mpeg"}
      / %p.pull-right= post.song.title
    
      

:javascript
  $(function(){
    $('audio,video').mediaelementplayer({
        loop: true,
        shuffle: true,
        playlist: true,
        audioHeight: 30,
        playlistposition: 'top',
        features: ['playlistfeature', 'prevtrack', 'playpause', 'nexttrack', 'loop', 'shuffle', 'playlist', 'current', 'progress', 'duration', 'volume'],
        iPadUseNativeControls: true,
        iPhoneUseNativeControls: true,
        AndroidUseNativeControls: true
    });
  });    

app/views/playlist_audio_player/index.js.erb
$("#playlist_player").html("<%= escape_javascript(render 'index') %>")

app/views/playlist_songs/_delete.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %h3 Delete Product
    .modal-body
      %ul.errors
      Are you sure you wish to delete
      = succeed "?" do
        %b= @playlist_song.song.title
    .modal-footer
      = link_to "Yes, Delete This Product",  playlist_playlist_song_path(@playlist_song), method: :delete, remote: true, class: "btn btn-danger"
      = link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" }

app/views/playlist_songs/index.html.haml
/ .col-sm-7
/   - @playlist_songs.each do |post| 
/     .row
/       .col-sm-3
/         .well
          
/           %img{:alt => "#{post.song.title}", :src => "#{post.song.art_work}"}/
/       .col-sm-9
/         .well
/           %p= post.song.title
/           = link_to playlist_playlist_audio_player_index_path, title: "#{post.song.title}", rel: 'tooltip' , remote: true do
/             %i.glyphicon.glyphicon-play
 

-  @playlist_songs.each do |post|
  .col-sm-6.col-md-4      
    .thumbnail
      %img{:alt => "#{post.song.title}", :src => "#{post.song.art_work}"}/
      .caption
        
        / %h3= post.title         
      = link_to playlist_playlist_audio_player_index_path, title: "#{post.song.title}", rel: 'tooltip' , remote: true do
        %i.glyphicon.glyphicon-play
      = link_to  playlist_song_path(post), :confirm => "Are you sure?" , method: :delete  do
        %i.glyphicon.glyphicon-minus
         
      / = link_to "Play" ,track_audio_player_index_path(post.id), title: "#{post.title}", rel: 'tooltip' , remote: true, class: "btn btn-primary"
  

/   %br   
%br
%br
%br       
#product-modal.modal.fade

app/views/playlist_songs/new.html.haml
#infinite-scrolling
  = will_paginate @feed 
.row
  - @feed.each do |post|
    .col-sm-6.col-md-4      
      .thumbnail
        %img{:alt => "#{post.title}", :src => "#{post.art_work}"}/
        .caption
          
          / %h3= post.title         
        = link_to song_audio_player_index_path(post.id), title: "#{post.title}", rel: 'tooltip' , remote: true do
          %i.glyphicon.glyphicon-play
        = link_to  new_playlist_song_playlist_song_path[@playlist,post.id], remote: false , method: :post  do
          %i.glyphicon.glyphicon-plus
           
        / = link_to "Play" ,track_audio_player_index_path(post.id), title: "#{post.title}", rel: 'tooltip' , remote: true, class: "btn btn-primary"
       
    %br          
#product-modal.modal.fade
 

app/views/playlist_songs/show.html.slim
h1 PlaylistSongs#show
p Find me in app/views/playlist_songs/show.html.slim

app/views/playlists/_edit.html.haml
.modal-dialog
  .modal-content
    = form_for @playlist, remote: true, html: { style: "display:inline;" } do |f|
      .modal-body
        %ul.errors
        .form-group
          = f.label :name, class:"control-label"
          = f.text_field :name, class: "form-control"
          = f.label :playlist_cover , class:"control-label"
          = f.text_field :playlist_cover, class: "form-control"
        
      .modal-footer
        = f.submit class: "btn btn-primary"
        = link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"}

app/views/playlists/_new.html.haml
.modal-dialog
  .modal-content
    = form_for @playlist, remote: true, html: { style: "display:inline;" } do |f|
      .modal-body
        %ul.errors
        .form-group
          = f.label :name, class:"control-label"
          = f.text_field :name, class: "form-control"
        
      .modal-footer
        = f.submit class: "btn btn-primary"
        = link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"}

app/views/playlists/create.js.erb
$("#product-modal").modal("hide");

app/views/playlists/edit.js.erb
$("#edit-modal").html("<%= escape_javascript(render 'edit') %>");
$('#edit-modal').modal('show');

app/views/playlists/index.html.haml
- @playlists.each do |playlist|
  .col-sm-6.col-md-4      
    .thumbnail
      %img{:alt => "#{playlist.name}", :src => "#{playlist.playlist_cover}"}/
      .caption
        
        / %h3= post.title         
      
      = link_to "View playlist" ,  playlist_playlist_songs_path(playlist),class: "btn btn-primary"
      = link_to "Add music" ,playlist_path(playlist),class: "btn btn-primary"
      = link_to "Edit playlist" ,  edit_playlist_path(playlist) , remote: true ,class: "btn btn-primary"
          

#edit-modal.modal.fade

app/views/playlists/new.js.erb
$("#product-modal").html("<%= escape_javascript(render 'new') %>");
$('#product-modal').modal('show');

app/views/playlists/show.html.haml
#infinite-scrolling
  = will_paginate @feed 
#search 
  .container 
    .row
      .col-md-5 
      = form_tag(song_search_index_path, :method => "get", id: "search-form") do
        = text_field_tag :search, params[:search], placeholder: "Search Track"
        = submit_tag "Search"

.row
  - @feed.each do |post|
    .col-sm-6.col-md-4      
      .thumbnail
        %img{:alt => "#{post.title}", :src => "#{post.art_work}"}/
        .caption
          
              
        = link_to song_audio_player_index_path(post.id), title: "#{post.title}", rel: 'tooltip' , remote: true do
          %i.glyphicon.glyphicon-play
        = link_to   playlist_song_playlist_songs_path(@playlist,post.id), remote: true , method: :post   do
          %i.glyphicon.glyphicon-plus
           
        
       
    %br          

 
            
         

app/views/song_search/index.html.haml
.row
  - @results.each do |post|
    .col-sm-6.col-md-4      
      .thumbnail
        %img{:alt => "#{post.title}", :src => "#{post.art_work}"}/
        .caption
          
              
        = link_to song_audio_player_index_path(post.id), title: "#{post.title}", rel: 'tooltip' , remote: true do
          %i.glyphicon.glyphicon-play
        / = link_to   playlist_song_playlist_songs_path(@playlist,post.id), remote: true , method: :post   do
        /   %i.glyphicon.glyphicon-plus
           
        
       
    %br          

 
            
         

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>